Environment Info:
 * Torchrun path: /gpfs/home3/ewalt/aurora-testbed/env/venv_h100/bin/torchrun
 * Python path: /gpfs/home3/ewalt/aurora-testbed/env/venv_h100/bin/python
 * Python version: Python 3.11.7
 * pytorch version: 2.5.1+cu124
|6|13098842|500|false|true|false|all|
Starting Aurora training script with arguments: Namespace(num_epochs=500, small=False, bf16=True, autocast=False, checkpointing_module_names=['Perceiver3DEncoder', 'Swin3DTransformerBackbone', 'Basic3DEncoderLayer', 'Basic3DDecoderLayer', 'Perceiver3DDecoder', 'LinearPatchReconstruction'])
Dummy dataset created with random data.
Model loaded and wrapped in DDP.
Loss and optimizer configured.
Epoch 1/500:   0%|          | 0/5 [00:00<?, ?it/s][rank0]: Traceback (most recent call last):
[rank0]:   File "/gpfs/home3/ewalt/aurora-testbed/train.py", line 125, in <module>
[rank0]:     main(args)
[rank0]:   File "/gpfs/home3/ewalt/aurora-testbed/train.py", line 114, in main
[rank0]:     except Exception as e: dist.destroy_process_group() ; raise e
[rank0]:                                                           ^^^^^^^
[rank0]:   File "/gpfs/home3/ewalt/aurora-testbed/train.py", line 113, in main
[rank0]:     try: train(args)
[rank0]:          ^^^^^^^^^^^
[rank0]:   File "/gpfs/home3/ewalt/aurora-testbed/train.py", line 105, in train
[rank0]:     loss.backward()
[rank0]:   File "/gpfs/home3/ewalt/aurora-testbed/env/venv_h100/lib64/python3.11/site-packages/torch/_tensor.py", line 581, in backward
[rank0]:     torch.autograd.backward(
[rank0]:   File "/gpfs/home3/ewalt/aurora-testbed/env/venv_h100/lib64/python3.11/site-packages/torch/autograd/__init__.py", line 347, in backward
[rank0]:     _engine_run_backward(
[rank0]:   File "/gpfs/home3/ewalt/aurora-testbed/env/venv_h100/lib64/python3.11/site-packages/torch/autograd/graph.py", line 825, in _engine_run_backward
[rank0]:     return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]: RuntimeError: CUDA error: an illegal memory access was encountered
[rank0]: Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Epoch 1/500:   0%|          | 0/5 [00:03<?, ?it/s]
E0710 15:08:49.029000 3200139 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 3200665) of binary: /gpfs/home3/ewalt/aurora-testbed/env/venv_h100/bin/python3.11
Traceback (most recent call last):
  File "/gpfs/home3/ewalt/aurora-testbed/env/venv_h100/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/gpfs/home3/ewalt/aurora-testbed/env/venv_h100/lib64/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/gpfs/home3/ewalt/aurora-testbed/env/venv_h100/lib64/python3.11/site-packages/torch/distributed/run.py", line 919, in main
    run(args)
  File "/gpfs/home3/ewalt/aurora-testbed/env/venv_h100/lib64/python3.11/site-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/gpfs/home3/ewalt/aurora-testbed/env/venv_h100/lib64/python3.11/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home3/ewalt/aurora-testbed/env/venv_h100/lib64/python3.11/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-10_15:08:49
  host      : gcn159.local.snellius.surf.nl
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3200665)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
srun: error: gcn159: task 0: Exited with exit code 1
srun: Terminating StepId=13098842.0

JOB STATISTICS
==============
Job ID: 13098842
Cluster: snellius
User/Group: ewalt/ewalt
State: RUNNING
Nodes: 1
Cores per node: 16
CPU Utilized: 00:00:00
CPU Efficiency: 0.00% of 00:32:16 core-walltime
Job Wall-clock time: 00:02:01
Memory Utilized: 0.00 MB
Memory Efficiency: 0.00% of 180.00 GB (180.00 GB/node)
WARNING: Efficiency statistics can only be obtained after the job has ended as seff tool is based on the accounting database data.
